//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteScripter.ResponderApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\__username_here__\\Google Drive\\MSA_Deploy\\RS.Responder.exe")]
        public string UpdatedCopyPath {
            get {
                return ((string)(this["UpdatedCopyPath"]));
            }
            set {
                this["UpdatedCopyPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\RemoteScripter.RequesterApp\\bin\\Debug\\Requests.txt")]
        public string RequestsFilePath {
            get {
                return ((string)(this["RequestsFilePath"]));
            }
            set {
                this["RequestsFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\RemoteScripter.RequesterApp\\bin\\Debug\\Responses.txt")]
        public string ResponsesFilePath {
            get {
                return ((string)(this["ResponsesFilePath"]));
            }
            set {
                this["ResponsesFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ProcessToRun.bat")]
        public string ProcessPathToRun {
            get {
                return ((string)(this["ProcessPathToRun"]));
            }
            set {
                this["ProcessPathToRun"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int OnChangeDelayMS {
            get {
                return ((int)(this["OnChangeDelayMS"]));
            }
        }
    }
}
